spring:
  application:
    name: jwt-demo22

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: coocon123!

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop #??? ?????? ??? ?? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

jwt:
  header: Authorization
  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
  #echo 'zzmin-tech-spring-boot-jwt-secret-zzmin-tech-spring-boot-jwt-secret'|base64
  #secret: enptaW4tdGVjaC1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0LXp6bWluLXRlY2gtc3ByaW5nLWJvb3Qtand0LXNlY3JldAo=
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    com.zzmin: DEBUG
# ALL < DEBUG < INFO < WARN < ERROR < FATAL < OFF


# H2
# => ??? ??? ??? ?????? ?? ???
# URL: http://localhost:8080/h2-console
# datasource? ??? ??? ???